service: despacho-granel-app

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:us-east-1:*:table/DespachoGranel

functions:
  createDespacho:
    handler: handler.createDespacho
    events:
      - http:
          path: despacho
          method: post
          cors: true

  getDespacho:
    handler: handler.getDespacho
    events:
      - http:
          path: despacho/{numeroGuia}
          method: get
          cors: true

  updateDespacho:
    handler: handler.updateDespacho
    events:
      - http:
          path: despacho/{numeroGuia}
          method: put
          cors: true

  deleteDespacho:
    handler: handler.deleteDespacho
    events:
      - http:
          path: despacho/{numeroGuia}
          method: delete
          cors: true

resources:
  Resources:
    DespachoGranel:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: DespachoGranel
        AttributeDefinitions:
          - AttributeName: numeroGuia
            AttributeType: S
        KeySchema:
          - AttributeName: numeroGuia
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

# Agregar el plugin para desarrollo local
plugins:
  - serverless-offline
