service: despacho-granel-app

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
        - dynamodb:Query
      Resource: 
        # Reemplaza con el ARN correcto de tu tabla de usuarios
        - arn:aws:dynamodb:us-east-1:207567761860:table/DespachoGranelTable
    - Effect: "Allow"
      Action:
        - execute-api:Invoke
      Resource: 
        - "arn:aws:execute-api:us-east-1:*:*"

functions:
  signup:
    handler: handler.signup
    events:
      - http:
          path: signup
          method: post
          
  login:
    handler: handler.login
    events:
      - http:
          path: login
          method: post
  
  home:
    handler: handler.home
    events:
      - http:
          path: home
          method: get

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: DespachoGranelTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-offline
